purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#514F50'
    - '#FFFEFA'
    - '#726D67'
    - '#211916'
    - '#8E8A89'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
name: Damon_A
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6109022
layout_spectrum: 0
